### PR TITLE
This adds Batman to the dictionary.

### PR DESCRIPTION
**Pull request by MMunglah**
Requesting permission to go forward with the merge?

### CODE REVIEW

**Review by osmart — CHANGES_REQUESTED** [review]
Do not like uppercase Bat in function names. Not PEP8

**Review by osmart — CHANGES_REQUESTED** [review]
once again `Bat_man` is not a PEP8 variable name should be `bat_man`snakecase

**Comment by MMunglah** [comment]
I have resolved the **conflicts** in regards to pull request #18 . Requesting **permission** to merge and to close issue #17

**Comment by osmart** [comment]
> I have resolved the **conflicts** in regards to pull request #18 . Requesting **permission** to merge and to close issue #17

Thanks for the corrections I was about to do them myself. The corrections are not **conflicts** though it would be possible for you to deal with the conflicts by 

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork

But this is advanced stuff - so I will deal with the conflicts - I have made a video of me doing this that I will show to the class tomorrow (9th December).

**Pull request merged**
